# -- 코드를 입력하세요
# SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SALES) as TOTAL_SALES
# FROM BOOK B
# JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
# JOIN BOOK_SALES C ON C.BOOK_ID = B.BOOK_ID 
# WHERE C.SALES_DATE >= '2022-01-01' AND C.SALES_DATE < 2022-02-01
# GROUP BY B.AUTHOR_ID, B.CATEGORY
# ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SALES) AS SALES
FROM BOOK B
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C ON C.BOOK_ID = B.BOOK_ID
WHERE C.SALES_DATE >= '2022-01-01' AND C.SALES_DATE < '2022-02-01'
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC;
