-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, B.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A 
JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID
JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE A.APNT_CNCL_YN = 'N' AND SUBSTRING(A.APNT_YMD, 1,10) = '2022-04-13' AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD
